/**
 * Declares the image modules that `import hero from "@/public/images/....webp"`
 * relies on (see components/features/hero/HeroSection.tsx).
 *
 * Next.js normally supplies this via the same reference in `next-env.d.ts` —
 * but that file is generated by `next dev`/`next build` and is gitignored, so
 * it does not exist on a fresh checkout. CI runs `tsc --noEmit` straight after
 * `npm install`, before anything has generated it, and every static image
 * import fails with TS2307. Committing the reference here keeps the typecheck
 * self-contained; it is harmless when `next-env.d.ts` is also present.
 */
/// <reference types="next/image-types/global" />
